# Changes here will be overwritten by Copier
_commit: v0.0.10
_src_path: https://github.com/KoenGreuell/vl-template-with-copier.git
development_plan: true
maturity_level_1: true
metadata_available: false
vl_abbreviation: content-copier
vl_name: vl-content-with-copier
vl_owner_forename: Koen
vl_owner_orcid: 0009-0008-7137-5877
vl_owner_surname: Greuell
